# Site settings
title: "Clacky AI 编程入门教程"
description: "专为零基础学习者设计的 AI 辅助编程教程"
baseurl: ""
url: "https://codinggirlsclub.github.io/ai-clacky-workshop-tutorial"

# Theme
remote_theme: just-the-docs/just-the-docs

# Color scheme
color_scheme: blue

# Logo
logo: "/assets/images/logo.png"

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation
nav_sort: case_insensitive

# Back to top link
back_to_top: true
back_to_top_text: "回到顶部"

# Footer
footer_content: "Copyright &copy; 2025 Coding Girls Club. 本教程采用 MIT 许可证。"

# GitHub Pages settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from build
exclude:
  - docs/
  - .github/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md
  - _includes/
  - _layouts/
  - assets/css/
  - assets/js/

# Site author
author:
  name: "Coding Girls Club"
  email: "support@clacky.ai"

# Social links
github_username: CodingGirlsClub
