# Site settings
title: "Clacky AI 编程入门教程"
description: "专为零基础学习者设计的 AI 辅助编程教程"
baseurl: "/ai-clacky-workshop-tutorial"
url: "https://codinggirlsclub.github.io"

# Theme
remote_theme: pmarsceill/just-the-docs

# Search
search_enabled: true

# Back to top link
back_to_top: true
back_to_top_text: "回到顶部"

# Footer
footer_content: "Copyright &copy; 2025 Coding Girls Club. 本教程采用 MIT 许可证。"

# GitHub Pages settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from build
exclude:
  - docs/
  - .github/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md

# Site author
author:
  name: "Coding Girls Club"
  email: "support@clacky.ai"

# Social links
github_username: CodingGirlsClub
